import { SignInButton, SignOutButton, useUser } from "@clerk/clerk-react";
import { type NextPage } from "next";
import Head from "next/head";
import { Dropdown } from "~/components/dropdown";
import { Button } from "~/components/ui/button";

const Home: NextPage = () => {

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-slate-600">
        {user.isLoaded && (
          <div>
            {
              user.isSignedIn ? (
                <div className="flex justify-center items-center flex-col text-center">
                  <h1 className="my-5 text-5xl font-bold text-slate-50">Welcome back to Transactions!</h1>
                  <Dropdown />
                </div>
              ) : (
                <div className="flex justify-center items-center flex-col text-center">
                  <h1 className="my-5 text-5xl font-bold text-slate-50">Welcome to Transactions!</h1>
                  <Button className="my-5 text-slate-50" variant="outline">
                    <SignInButton />
                  </Button>
                </div>
              )
            }

          </div>
        )
        }
      </main>
    </>
  );
};

export default Home;
